import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Main from '../components/Main'
// import Navbar from '../components/Navbar'
import Projects from '../components/Projects'
import Skills from '../components/Skills'
import Contact from '../components/Contact'
import Spacer from '@/components/Spacer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Dahlak | Full-Stack DevOps Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/dklogo1.png" />
      </Head>
      {/* <Navbar /> */}
      <Spacer />
      <Main />
      <Spacer />
      <About />
      <Spacer />
      <Skills />
      <Spacer />
      <Projects />
      <Spacer />
      <Contact />
    </div>
  )
}
